#!/bin/bash
# Script by Salvo 'LtWorf' Tomaselli.

if [ -z $CONFFILE ]
then
	CONFFILE=/etc/autoshutdown.conf
fi

if [ -e $CONFFILE ]
then
	. $CONFFILE
else
	DELAY=120
	ATTEMPTS=8
	COMMAND="init 0"
fi

used_attempts=0

echo "Delay is set to $DELAY seconds"
echo "Will do $ATTEMPTS attempts"

	while true
	do
		sleep $DELAY;
		users=`LANG=c who -q | grep "users" | cut -d = -f 2`
		
		if [ $users = '0' ] 
		then			
			if [ $used_attempts = $ATTEMPTS ]
			then
				$COMMAND
			fi
			used_attempts=`echo $used_attempts+1 | bc`			
		else
			used_attempts=0
		fi

	done
