#!/bin/bash
# Script by Salvo 'LtWorf' Tomaselli.

user=`whoami`
if [ $user != "root" ]
then
	echo "Must be root"
	exit 5
fi

if [ -e /run/autoshutdown ]
then
	echo /run/autoshutdown is already there
	exit 2
fi

echo $$ > /run/autoshutdown

if [ -z $CONFFILE ]
then
	CONFFILE=/etc/autoshutdown.conf
fi

if [ -e $CONFFILE ]
then
	. $CONFFILE
else
	DELAY=120
	ATTEMPTS=8
	COMMAND="init 0"
fi

used_attempts=0

echo "Delay is set to $DELAY seconds"
echo "Will do $ATTEMPTS attempts"

	while true
	do
		sleep $DELAY;
		users=`LANG=c who -q | grep "users" | cut -d = -f 2`
		echo Users: $users
		if [ $users = '0' ]
		then
			if [ $used_attempts = $ATTEMPTS ]
			then
				echo Running $COMMAND
				echo "$COMMAND" | bash
			fi
			echo Attempts left: $used_attempts
			used_attempts=`echo $used_attempts + 1 | bc`
		else
			used_attempts=0
		fi

	done
