.TH autoshutdown 8 "Feb 23, 2006"

.SH NAME
.B autoshutdown
\- Daemon to turn off the computer when there are no users

.SH SYNOPSIS
.B "/etc/init.d/autoshutdown"
[
.B options
]

.SH DESCRIPTION

\fBAutoshutdown\fP is a daemon, it checks if there are users logged in on each delay. If there are 0 users it will run a command (init 0 by default).

The daemon will count the users. If they are more than 0 it will go to sleep for a certain amount of time.
If there are 0 users it may give another chance to login, or switch to runlevel 0, depending on configuration.

.SH Configuration
Configuration file is /etc/autoshutdown.conf, but can be overridden by setting CONFFILE

.SH FILES
.TP
/usr/bin/autoshutdown
Script that does the check.

.TP
/etc/init.d/autoshutdown
Script to use to launch the daemon.

.TP
/etc/autoshutdown.conf
Configuration file



.SH "SEE ALSO"
.BR init (8)

.SH VERSION
\fBautoshutdown\fP 1.0.0

.SH WEB
https://github.com/ltworf/autoshutdown

.SH AUTHOR
This page was written by Salvo "LtWorf" Tomaselli <tiposchi@tiscali.it>
